name: pinhalense
description: Automação e IA para o setor de projetos

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # CSV e Excel
  csv: ^6.0.0
  excel: ^4.0.3
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  
  # IA e Câmera
  tflite_flutter: ^0.10.4
  image_picker: ^1.1.2
  image: ^4.1.7
  permission_handler: ^11.3.0

flutter:
  assets:
    - assets/modelo/
